# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # DÃ©clare le controller AuthController comme service
    App\Controller\AuthController:
    
        arguments:
            $jwtEncoder: '@lexik_jwt_authentication.encoder'
        tags: ['controller.service_arguments']
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
   
       

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Repository\admin\AdministrateurRepositoryInterface:
            alias: App\Repository\admin\AdministrateurRepository
    App\Repository\admin\DashboardRepositoryInterface:
            alias: App\Repository\admin\DashboardRepository
    App\Repository\auth\UserRepositoryInterface:
            alias: App\Repository\auth\UserRepository
    App\Repository\client\ClientRepositoryInterface:
            alias: App\Repository\client\ClientRepository
